train:
    image_feat_mode: frozen_local
    text_feat_mode: full
    batch_size: 16
    val_batch_size: 16
    accum_steps: 64
    accum_cpu_offload: false
    datasets: {}
    language: en
    data_fraction: 1
    saveckp_freq: 1
    resume_ckp: true
    seed: 42
    workers: 1
    val_workers: 1
    prefetch_factor: 1
    load_fp16: true
    mixed_precision: bf16  # "no", "fp16", "bf16", or "fp8"
    pin_memory: true
    persistent_workers: false  # Set to false to prevent memory accumulation in workers
    drop_last: true
    use_gds: false
    log_freq: 1
    log_grad_freq: 100
    val_freq: 1
    val_first: 0
    random_flip: 0.5
    validation_tasks: []
    test_tasks:
        - configs/tasks/lists/evals.yaml
optim:
    epochs: 0
    weight_decay: 0.01
    base_lr: 1.0e-04  # 0.001
    lr: 0.  # will be set after applying scaling rule
    warmup_epochs: 1
    freeze_image_backbone_epochs: 0  # 10 for siglip training after dino  # -1 means fully freeze backbone
    freeze_patch_embedding: true  # freeze the window-level patch embedding layer
    freeze_image_projection: false
    freeze_text_projection: false
    image_backbone_grad_checkpoint_every: 1
    text_backbone_grad_checkpoint: true
    freeze_image_proj_last_layer_epochs: 0
    freeze_text_proj_last_layer_epochs: 0
    min_lr: 1.0e-06
    llrd_factor: 0.9
    patch_embed_lr_mult: 0  # 0.2
    projection_head_wd_mult: 1.0
    clip_grad_norm: 1.0
    scaling_rule: sqrt_wrt_1024
    adamw_beta1: 0.9
    adamw_beta2: 0.95
    optimizer: adamw
model:
    pretrained_weights: null
    learnable_t: true
    learnable_b: true
    init_t: 2.3026  # ~log(10)
    init_b: -10.0
    normalize: true
    backbone_kwargs:
        init_values: 1e-3  # layer scale, will be overwritten by pretrained checkpoint
        rope_kwargs:
            base: 1000.0  
            rescale_coords: 2.0  # rope augmentation, s in [0.5, 2.0]
    feature_combiner_kwargs:
        init_values: 1e-3  # layer scale, will be overwritten by pretrained checkpoint
        rope_kwargs:
            base: 100.0  
            rescale_coords: 2.0  # rope augmentation, s in [0.5, 2.0]
    text_backbone_kwargs:
        tokenizer_max_length: 1024
